# Generated by Django 4.1.6 on 2023-03-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
