# Generated by Django 4.1.6 on 2023-03-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_collection_date_alter_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField(max_length=12, null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.collection')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.project')),
            ],
        ),
    ]
